<a href="https://colab.research.google.com/github/louvrehes/Numerical-Methods/blob/main/Matrix%20Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name**: ANGELO, Jamaica Joy S.
<br>**Course**: Numerical Methods
<br>**Section**: 58101

## Matrix and its Operations

In [2]:
import numpy as np

In [9]:
a = np.array([1, 2, 3]) # This is a 1 x 3 array
a

array([1, 2, 3])

In [20]:
a[0]= 4
a

array([4, 2, 3])

In [15]:
b = np.array([
              [1, 2, 3], # This is an example of a 2x3 matrix
              [4, 5, 6]
])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [19]:
b = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

b[0,0] = 7
print(b)



array([[7, 2, 3],
       [4, 5, 6]])

In [21]:
# Square Matrix
c = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
d = np.full((2,2),7)
print(d)

[[7 7]
 [7 7]]


### <b>Identity Matrix

In [23]:
e = np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


### <b>Diagonal Matrix

In [27]:
e = np.diagonal([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])
print(e)

[1 5 9]


### <b>Empty Matrix

In [29]:
f = np.empty((0, 10))
print(f)

[]


### <b>Zeros Matrix

In [30]:
g = np.zeros((2,2))
print(g)

[[0. 0.]
 [0. 0.]]


In [33]:
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)
print(e+g) # This is the code to get the summation of matrices e and g
print(e-g) # This is the code to get the difference of matrices e and g
print(g-e)

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
