<a href="https://colab.research.google.com/github/louvrehes/Numerical-Methods/blob/main/Python%20Exercise%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: ANGELO, Jamaica Joy S.
<br>Student Number: 201811828
<br>Section: 58101
<br>Course: Numerical Methods

### <b><u>Matrix and its Operations

Create a Numpy that performs the operations of given matrices.
1. Sum = A + B
2. Difference 1 = A - B
3. Difference 2 = B - A

In [1]:
import numpy as np

### <b>Sum = A + B

In [6]:
A = np.array([
              [-5, 0],
              [4, 1]
])

B = np.array([
              [6, -3],
              [2, 3]
])
print(A+B)

[[ 1 -3]
 [ 6  4]]


### <b>Difference 1 = A - B

In [9]:
A = np.array([
              [-5, 0],
              [4, 1]
])

B = np.array([
              [6, -3],
              [2, 3]
])
print(A-B)

[[-11   3]
 [  2  -2]]


### <b>Difference 2 = B - A

In [10]:
A = np.array([
              [-5, 0],
              [4, 1]
])

B = np.array([
              [6, -3],
              [2, 3]
])
print(B-A)

[[11 -3]
 [-2  2]]
